### ISSUE TITLE
Citation not displayed properly

### ISSUE THREAD

**Issue by guillaumelobet** [mfenner/pandoc-jats#3]
Hello @mfenner, 

Thanks for this great addition to pandoc, it works great! 

I just have an issue with the citations. Theyare correctly reference in the text, but are displayed like this:

    <xref ref-type="bibr" rid="ref-2">">ref-2"></xref>

Is this an issue with the lua file?

Best, 

Guillaume

**Comment by mfenner** [comment]
Seems like an issue with the regex I am using in Lua. Are there other references right before or after this one?

**Comment by mfenner** [comment]
This is fixed with the latest release.

**Comment by guillaumelobet** [comment]
Thanks a lot!
