### ISSUE TITLE
Reference xml tags

### ISSUE THREAD

**Issue by VidhyaApple** [mfenner/pandoc-jats#5]
In article, reference list is in paragraph style when converting from md file to xml (jats)format.

output:
   ` <ref-list>`
    `<title>References</title> `
    `Anderson, E. R., and L. C. Mayes. 2010. “Race/ethnicity and Internalizing Disorders in Youth: A Review.” <italic>Clinical Psychology Review</italic> 30: 338–48. doi:10.1016/j.cpr.2009.12.008.`
    `</ref-list>`
Is there any way to get the xml-jats output like,`<surname><lastname>` tags in the reference list?

**Comment by mfenner** [comment]
Make sure you use `jats.csl` included in the `examples` folder, e.g. by using the `--csl=examples/jats.csl` command-line flag.
