### ISSUE TITLE
Latex to JATS XML

### ISSUE THREAD

**Issue by VidhyaApple** [mfenner/pandoc-jats#7]
I need to convert latex file to jats xml.  I tried latex to md to jats using pandoc and also tried  directly from latex to jats. But which would be the effective way to convert  the latex into jats xml

**Comment by mfenner** [comment]
There is no advantage in first converting to markdown, so you should go directly from LaTex to jats. The tricky bit about JATS is all the metadata you need, but you can also provide at least some of them via the command line.

**Comment by huhsoleil** [comment]
Dear Martin,
Do you know where is the program or source of La Tex to JATS converter?

Thank you.

**Comment by mfenner** [comment]
`pandoc-jats` could be used as a LaTeX to JATS converter, as LaTex is one of many input formats that Pandoc accepts.
